### ISSUE TITLE
Make image linkable

### ISSUE THREAD

**Issue by amitaibu** [Gizra/yesoders#16]
![haskellers](https://cloud.githubusercontent.com/assets/125707/19219070/38bdc28c-8e12-11e6-87a3-8412b0f192e4.jpg)

**Comment by nedSaf** [comment]
Waiting on [this](https://github.com/haskell/cabal/pull/3982) to be merged for me to be able to install Haskell on macOS Sierra.

**Comment by amitaibu** [comment]
Are you trying to install with stack? Follow the installation notes in the yesod website.

**Comment by nedSaf** [comment]
Yes I tried installing with Stack build tool, I'll try the instruction in Yesod website, thanks.

**Comment by nedSaf** [comment]
Update: Same result, this issue describes the problem https://github.com/commercialhaskell/stack/issues/2577

**Comment by amitaibu** [comment]
I see. You can probably use docker instead.

**Comment by nedSaf** [comment]
Ok, I'll check it out
